### ISSUE TITLE
How to build ThermalSolution?

### ISSUE THREAD

**Issue by F1orian** [zhen-zen/ThermalSolution#5]
I'm trying to build the recent verision of this project using Xcode. However I'm not having any success with that. Could you specify the build instructions? The ones in the README of YogaSMC sadly did not help.
Thanks a lot!

**Comment by zhen-zen** [comment]
It should be the same, since both projects relies on Lilu and Xcode will ask for the headers. You can also check the GitHub Actions workflow under .github for reference.
